# Generated by Django 5.2.17 on 2026-09-24 17:32

import uuid

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=8)),
                ('date', models.DateField()),
                ('total_income', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_expense', models.DecimalField(decimal_places=2, max_digits=18)),
                ('net_balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('is_stale', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stale_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date', 'period'),
                'indexes': [models.Index(fields=['user', 'is_stale', 'period', 'date'], name='dashboard_owner_stale_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'period', 'date'), name='dashboard_owner_period_date_unique'), models.CheckConstraint(condition=models.Q(('period__in', ('daily', 'weekly', 'monthly'))), name='dashboard_valid_period'), models.CheckConstraint(condition=models.Q(('total_income__gte', 0)), name='dashboard_income_nonnegative'), models.CheckConstraint(condition=models.Q(('total_expense__gte', 0)), name='dashboard_expense_nonnegative'), models.CheckConstraint(condition=models.Q(('net_balance', django.db.models.expressions.CombinedExpression(models.F('total_income'), '-', models.F('total_expense')))), name='dashboard_net_matches_totals'), models.CheckConstraint(condition=models.Q(models.Q(('is_stale', True), ('stale_at__isnull', False)), models.Q(('is_stale', False), ('stale_at__isnull', True)), _connector='OR'), name='dashboard_stale_timestamp_consistent')],
            },
        ),
    ]
