# Generated by Django 5.2.17 on 2026-10-05 16:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ApartmentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=20)),
                ('floor', models.IntegerField(default=1)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='rentals.housemodel')),
            ],
            options={
                'ordering': ('number', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PaymentRecordModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='rentals.apartmentmodel')),
            ],
            options={
                'ordering': ('-payment_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='UtilityReadingModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('utility_type', models.CharField(choices=[('WATER', 'Water'), ('ELECTRICITY', 'Electricity'), ('GAS', 'Gas')], max_length=20)),
                ('reading_date', models.DateField()),
                ('current_reading', models.DecimalField(decimal_places=2, max_digits=8)),
                ('previous_reading', models.DecimalField(decimal_places=2, max_digits=8)),
                ('consumption', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utility_readings', to='rentals.apartmentmodel')),
            ],
            options={
                'ordering': ('-reading_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='DocumentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('ID_CARD', 'ID Card'), ('LEASE_CONTRACT', 'Lease Contract'), ('EMPLOYMENT_CERTIFICATE', 'Employment Certificate'), ('OTHER', 'Other')], max_length=50)),
                ('file_url', models.URLField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='rentals.apartmentmodel')),
            ],
            options={
                'ordering': ('-uploaded_at', '-id'),
                'indexes': [models.Index(fields=['apartment', 'document_type'], name='document_apartment_type_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('document_type__in', ('ID_CARD', 'LEASE_CONTRACT', 'EMPLOYMENT_CERTIFICATE', 'OTHER'))), name='document_valid_type')],
            },
        ),
        migrations.AddIndex(
            model_name='housemodel',
            index=models.Index(fields=['owner', 'name'], name='house_owner_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='housemodel',
            constraint=models.CheckConstraint(condition=models.Q(('name__regex', '^\\s*$'), _negated=True), name='house_name_nonblank'),
        ),
        migrations.AddIndex(
            model_name='apartmentmodel',
            index=models.Index(fields=['house', 'number'], name='apartment_house_number_idx'),
        ),
        migrations.AddConstraint(
            model_name='apartmentmodel',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_rent__gt', 0)), name='apartment_rent_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='apartmentmodel',
            constraint=models.CheckConstraint(condition=models.Q(('floor__gte', 0)), name='apartment_floor_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='apartmentmodel',
            constraint=models.CheckConstraint(condition=models.Q(('number__regex', '^\\s*$'), _negated=True), name='apartment_number_nonblank'),
        ),
        migrations.AddIndex(
            model_name='paymentrecordmodel',
            index=models.Index(fields=['apartment', '-payment_date'], name='payment_apart_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentrecordmodel',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('PENDING', 'PARTIAL', 'PAID', 'OVERDUE'))), name='payment_record_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='paymentrecordmodel',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_record_amount_gt_zero'),
        ),
        migrations.AddIndex(
            model_name='utilityreadingmodel',
            index=models.Index(fields=['apartment', 'utility_type', '-reading_date'], name='utility_reading_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='utilityreadingmodel',
            constraint=models.UniqueConstraint(fields=('apartment', 'utility_type', 'reading_date'), name='utility_reading_unique_apt_util_date'),
        ),
        migrations.AddConstraint(
            model_name='utilityreadingmodel',
            constraint=models.CheckConstraint(condition=models.Q(('utility_type__in', ('WATER', 'ELECTRICITY', 'GAS'))), name='utility_reading_valid_type'),
        ),
        migrations.AddConstraint(
            model_name='utilityreadingmodel',
            constraint=models.CheckConstraint(condition=models.Q(('current_reading__gte', models.F('previous_reading'))), name='utility_reading_current_gte_previous'),
        ),
        migrations.AddConstraint(
            model_name='utilityreadingmodel',
            constraint=models.CheckConstraint(condition=models.Q(('consumption__gte', 0)), name='utility_reading_consumption_nonnegative'),
        ),
    ]
