# Generated by Django 5.2.18 on 2026-10-06 22:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('importance', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=8)),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('todo', 'Todo'), ('doing', 'Doing'), ('done', 'Done')], default='todo', max_length=8)),
                ('is_checked_by_llm', models.BooleanField(default=False)),
                ('llm_evaluation_failed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.goalmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='DailyPlanModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('generated_by_llm', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_plans', to=settings.AUTH_USER_MODEL)),
                ('tasks', models.ManyToManyField(blank=True, related_name='daily_plans', to='tasks.taskmodel')),
            ],
            options={
                'ordering': ('-date', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='goalmodel',
            index=models.Index(fields=['user', 'status'], name='goal_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='goalmodel',
            index=models.Index(fields=['user', '-due_date'], name='goal_owner_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='goalmodel',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('active', 'completed', 'archived'))), name='goal_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='goalmodel',
            constraint=models.CheckConstraint(condition=models.Q(('name__regex', '^\\s*$'), _negated=True), name='goal_name_nonblank'),
        ),
        migrations.AddIndex(
            model_name='taskmodel',
            index=models.Index(fields=['user', 'status'], name='task_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='taskmodel',
            index=models.Index(fields=['user', 'due_date'], name='task_owner_due_idx'),
        ),
        migrations.AddIndex(
            model_name='taskmodel',
            index=models.Index(fields=['goal'], name='task_goal_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskmodel',
            constraint=models.CheckConstraint(condition=models.Q(('importance__in', ('low', 'medium', 'high'))), name='task_valid_importance'),
        ),
        migrations.AddConstraint(
            model_name='taskmodel',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('todo', 'doing', 'done'))), name='task_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='taskmodel',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_hours__gte', 0)), name='task_hours_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='taskmodel',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_hours__lte', 999999.99)), name='task_hours_lte_max'),
        ),
        migrations.AddIndex(
            model_name='dailyplanmodel',
            index=models.Index(fields=['user', '-date'], name='dailyplan_owner_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyplanmodel',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='dailyplan_unique_user_date'),
        ),
        migrations.AddConstraint(
            model_name='dailyplanmodel',
            constraint=models.CheckConstraint(condition=models.Q(('total_hours__gte', 0)), name='dailyplan_hours_gte_zero'),
        ),
    ]
