"""Tasks application use cases."""

from apps.tasks.application.use_cases.daily_plans import (
    AddTaskToDailyPlan,
    DeleteDailyPlan,
    GenerateDailyPlanWithLlm,
    GetDailyPlan,
    GetOrCreateDailyPlan,
    ListDailyPlans,
    RemoveTaskFromDailyPlan,
    UpdateDailyPlan,
)
from apps.tasks.application.use_cases.goals import (
    CreateGoal,
    DeleteGoal,
    GetGoal,
    LinkTaskToGoal,
    ListUserGoals,
    UnlinkTaskFromGoal,
    UpdateGoal,
)
from apps.tasks.application.use_cases.tasks import (
    CreateTask,
    DecomposeOverwhelmingTask,
    DeleteTask,
    EvaluateTaskWithLlm,
    GetTask,
    ListUserTasks,
    MarkTaskAsDoing,
    MarkTaskAsDone,
    PromoteTaskPriority,
    UpdateTask,
)

__all__ = (
    "AddTaskToDailyPlan",
    "CreateGoal",
    "CreateTask",
    "DecomposeOverwhelmingTask",
    "DeleteDailyPlan",
    "DeleteGoal",
    "DeleteTask",
    "EvaluateTaskWithLlm",
    "GenerateDailyPlanWithLlm",
    "GetDailyPlan",
    "GetGoal",
    "GetOrCreateDailyPlan",
    "GetTask",
    "LinkTaskToGoal",
    "ListDailyPlans",
    "ListUserGoals",
    "ListUserTasks",
    "MarkTaskAsDoing",
    "MarkTaskAsDone",
    "PromoteTaskPriority",
    "RemoveTaskFromDailyPlan",
    "UnlinkTaskFromGoal",
    "UpdateDailyPlan",
    "UpdateGoal",
    "UpdateTask",
)
