"""Pure rentals domain model and business rules."""

from apps.rentals.domain.entities import (
    Apartment,
    Document,
    House,
    PaymentRecord,
    UtilityReading,
)
from apps.rentals.domain.exceptions import (
    ApartmentNotFound,
    DocumentNotFound,
    HouseNotFound,
    InvalidAddress,
    InvalidPaymentAmount,
    InvalidReading,
    PaymentRecordNotFound,
    RentalsDomainError,
    UtilityReadingNotFound,
)
from apps.rentals.domain.value_objects import (
    DOCUMENT_TYPE_CHOICES,
    PAYMENT_STATUS_CHOICES,
    UTILITY_TYPE_CHOICES,
    Address,
    ApartmentId,
    ApartmentNumber,
    DocumentId,
    DocumentType,
    HouseId,
    MonthlyRent,
    PaymentAmount,
    PaymentRecordId,
    PaymentStatus,
    Reading,
    UnitCost,
    UserId,
    UtilityReadingId,
    UtilityType,
)

__all__ = (
    "DOCUMENT_TYPE_CHOICES",
    "PAYMENT_STATUS_CHOICES",
    "UTILITY_TYPE_CHOICES",
    "Address",
    "Apartment",
    "ApartmentId",
    "ApartmentNotFound",
    "ApartmentNumber",
    "Document",
    "DocumentId",
    "DocumentNotFound",
    "DocumentType",
    "House",
    "HouseId",
    "HouseNotFound",
    "InvalidAddress",
    "InvalidPaymentAmount",
    "InvalidReading",
    "MonthlyRent",
    "PaymentAmount",
    "PaymentRecord",
    "PaymentRecordId",
    "PaymentRecordNotFound",
    "PaymentStatus",
    "Reading",
    "RentalsDomainError",
    "UnitCost",
    "UserId",
    "UtilityReading",
    "UtilityReadingId",
    "UtilityReadingNotFound",
    "UtilityType",
)
