# Generated by Django 5.2.17 on 2026-09-24 16:31

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('investment', 'Investment'), ('savings', 'Savings')], default='expense', max_length=12)),
                ('category', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date', '-created_at', '-id'),
                'indexes': [models.Index(fields=['user', '-date', '-created_at', '-id'], name='transaction_owner_date_idx')],
                'constraints': [
                    models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='transaction_amount_gt_zero'),
                    models.CheckConstraint(condition=models.Q(('transaction_type__in', ['income', 'expense', 'investment', 'savings'])), name='transaction_valid_type'),
                    models.CheckConstraint(condition=~models.Q(('category__regex', '^\\s*$')), name='transaction_category_nonblank'),
                ],
            },
        ),
    ]
