# Generated by Django 5.2.17 on 2026-10-02 00:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('language', models.CharField(default='es', max_length=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('date_format', models.CharField(choices=[('YYYY-MM-DD', 'ISO 8601 (YYYY-MM-DD)'), ('DD/MM/YYYY', 'Day first (DD/MM/YYYY)'), ('MM/DD/YYYY', 'Month first (MM/DD/YYYY)')], default='YYYY-MM-DD', max_length=20)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('date_format__in', ('YYYY-MM-DD', 'DD/MM/YYYY', 'MM/DD/YYYY'))), name='profile_valid_date_format'), models.CheckConstraint(condition=models.Q(models.Q(('first_name__regex', '^\\s*$'), _negated=True), models.Q(('last_name__regex', '^\\s*$'), _negated=True), _connector='OR'), name='profile_name_nonblank')],
            },
        ),
    ]
